// Generated by CoffeeScript 1.10.0
(function() {
  var Thingy;

  Thingy = function() {
    var things;
    things = {};
    return {
      add: function(thingId, fn) {
        return things[thingId] = {
          fn: fn,
          instance: null
        };
      },
      start: function(thingId) {
        things[thingId].instance = things[thingId].fn(null);
        if (init) {
          return Promise.resolve(things[thingId].instance.init);
        }
      },
      stop: function(thingId) {
        var thing;
        thing = things[thingId];
        if (thing.instance) {
          thing.instance.destroy();
          return thing.instance = null;
        }
      },
      all: function(mode) {
        var i, len, results, thing;
        if (!(mode === "start" || mode === "stop")) {
          return null;
        }
        results = [];
        for (i = 0, len = things.length; i < len; i++) {
          thing = things[i];
          if (things.hasOwnProperty(thing)) {
            results.push(this[mode](thing));
          } else {
            results.push(void 0);
          }
        }
        return results;
      }
    };
  };

  module.exports = new Thingy();

}).call(this);
